//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GenericFileTransferClient.GenericFileTransferService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Report", Namespace="http://schemas.datacontract.org/2004/07/GenericFileTransfer.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Report : GenericFileTransferClient.GenericFileTransferService.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GenericFileTransferClient.GenericFileTransferService.Column[] ColumnsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HeaderRowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReportNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ResultRowField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GenericFileTransferClient.GenericFileTransferService.Column[] Columns {
            get {
                return this.ColumnsField;
            }
            set {
                if ((object.ReferenceEquals(this.ColumnsField, value) != true)) {
                    this.ColumnsField = value;
                    this.RaisePropertyChanged("Columns");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Header {
            get {
                return this.HeaderField;
            }
            set {
                if ((this.HeaderField.Equals(value) != true)) {
                    this.HeaderField = value;
                    this.RaisePropertyChanged("Header");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HeaderRow {
            get {
                return this.HeaderRowField;
            }
            set {
                if ((this.HeaderRowField.Equals(value) != true)) {
                    this.HeaderRowField = value;
                    this.RaisePropertyChanged("HeaderRow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReportName {
            get {
                return this.ReportNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportNameField, value) != true)) {
                    this.ReportNameField = value;
                    this.RaisePropertyChanged("ReportName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResultRow {
            get {
                return this.ResultRowField;
            }
            set {
                if ((this.ResultRowField.Equals(value) != true)) {
                    this.ResultRowField = value;
                    this.RaisePropertyChanged("ResultRow");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StructuralObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GenericFileTransferClient.GenericFileTransferService.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GenericFileTransferClient.GenericFileTransferService.Column))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GenericFileTransferClient.GenericFileTransferService.Report))]
    public partial class StructuralObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityObject", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GenericFileTransferClient.GenericFileTransferService.Column))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GenericFileTransferClient.GenericFileTransferService.Report))]
    public partial class EntityObject : GenericFileTransferClient.GenericFileTransferService.StructuralObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GenericFileTransferClient.GenericFileTransferService.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GenericFileTransferClient.GenericFileTransferService.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Column", Namespace="http://schemas.datacontract.org/2004/07/GenericFileTransfer.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Column : GenericFileTransferClient.GenericFileTransferService.EntityObject {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GenericFileTransferClient.GenericFileTransferService.Report ReportField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ReportIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GenericFileTransferClient.GenericFileTransferService.EntityReferenceOfReport6W5yNmin ReportReferenceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Header {
            get {
                return this.HeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.HeaderField, value) != true)) {
                    this.HeaderField = value;
                    this.RaisePropertyChanged("Header");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GenericFileTransferClient.GenericFileTransferService.Report Report {
            get {
                return this.ReportField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportField, value) != true)) {
                    this.ReportField = value;
                    this.RaisePropertyChanged("Report");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ReportId {
            get {
                return this.ReportIdField;
            }
            set {
                if ((this.ReportIdField.Equals(value) != true)) {
                    this.ReportIdField = value;
                    this.RaisePropertyChanged("ReportId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GenericFileTransferClient.GenericFileTransferService.EntityReferenceOfReport6W5yNmin ReportReference {
            get {
                return this.ReportReferenceField;
            }
            set {
                if ((object.ReferenceEquals(this.ReportReferenceField, value) != true)) {
                    this.ReportReferenceField = value;
                    this.RaisePropertyChanged("ReportReference");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKey", Namespace="http://schemas.datacontract.org/2004/07/System.Data", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class EntityKey : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityContainerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GenericFileTransferClient.GenericFileTransferService.EntityKeyMember[] EntityKeyValuesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntitySetNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityContainerName {
            get {
                return this.EntityContainerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityContainerNameField, value) != true)) {
                    this.EntityContainerNameField = value;
                    this.RaisePropertyChanged("EntityContainerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GenericFileTransferClient.GenericFileTransferService.EntityKeyMember[] EntityKeyValues {
            get {
                return this.EntityKeyValuesField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyValuesField, value) != true)) {
                    this.EntityKeyValuesField = value;
                    this.RaisePropertyChanged("EntityKeyValues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitySetName {
            get {
                return this.EntitySetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EntitySetNameField, value) != true)) {
                    this.EntitySetNameField = value;
                    this.RaisePropertyChanged("EntitySetName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityKeyMember", Namespace="http://schemas.datacontract.org/2004/07/System.Data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GenericFileTransferClient.GenericFileTransferService.Report[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GenericFileTransferClient.GenericFileTransferService.Report))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GenericFileTransferClient.GenericFileTransferService.Column[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GenericFileTransferClient.GenericFileTransferService.Column))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GenericFileTransferClient.GenericFileTransferService.EntityObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GenericFileTransferClient.GenericFileTransferService.StructuralObject))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GenericFileTransferClient.GenericFileTransferService.EntityReferenceOfReport6W5yNmin))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GenericFileTransferClient.GenericFileTransferService.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GenericFileTransferClient.GenericFileTransferService.RelatedEnd))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GenericFileTransferClient.GenericFileTransferService.EntityKey))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GenericFileTransferClient.GenericFileTransferService.EntityKeyMember[]))]
    public partial class EntityKeyMember : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReferenceOfReport6W5yNmin", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    public partial class EntityReferenceOfReport6W5yNmin : GenericFileTransferClient.GenericFileTransferService.EntityReference {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityReference", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GenericFileTransferClient.GenericFileTransferService.EntityReferenceOfReport6W5yNmin))]
    public partial class EntityReference : GenericFileTransferClient.GenericFileTransferService.RelatedEnd {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GenericFileTransferClient.GenericFileTransferService.EntityKey EntityKeyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GenericFileTransferClient.GenericFileTransferService.EntityKey EntityKey {
            get {
                return this.EntityKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityKeyField, value) != true)) {
                    this.EntityKeyField = value;
                    this.RaisePropertyChanged("EntityKey");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RelatedEnd", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Objects.DataClasses")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GenericFileTransferClient.GenericFileTransferService.EntityReference))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(GenericFileTransferClient.GenericFileTransferService.EntityReferenceOfReport6W5yNmin))]
    public partial class RelatedEnd : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GenericFileTransferService.GenericFileTransferService")]
    public interface GenericFileTransferService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenericFileTransferService/GetAllReports", ReplyAction="http://tempuri.org/GenericFileTransferService/GetAllReportsResponse")]
        GenericFileTransferClient.GenericFileTransferService.Report[] GetAllReports();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenericFileTransferService/GetColumnsByReport", ReplyAction="http://tempuri.org/GenericFileTransferService/GetColumnsByReportResponse")]
        GenericFileTransferClient.GenericFileTransferService.Column[] GetColumnsByReport(System.Guid reportId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenericFileTransferService/UpsertReport", ReplyAction="http://tempuri.org/GenericFileTransferService/UpsertReportResponse")]
        void UpsertReport(GenericFileTransferClient.GenericFileTransferService.Report report);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenericFileTransferService/DeleteReport", ReplyAction="http://tempuri.org/GenericFileTransferService/DeleteReportResponse")]
        void DeleteReport(GenericFileTransferClient.GenericFileTransferService.Report report);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenericFileTransferService/UpsertColumn", ReplyAction="http://tempuri.org/GenericFileTransferService/UpsertColumnResponse")]
        void UpsertColumn(GenericFileTransferClient.GenericFileTransferService.Column column);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenericFileTransferService/DeleteColumn", ReplyAction="http://tempuri.org/GenericFileTransferService/DeleteColumnResponse")]
        void DeleteColumn(GenericFileTransferClient.GenericFileTransferService.Column column);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GenericFileTransferServiceChannel : GenericFileTransferClient.GenericFileTransferService.GenericFileTransferService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GenericFileTransferServiceClient : System.ServiceModel.ClientBase<GenericFileTransferClient.GenericFileTransferService.GenericFileTransferService>, GenericFileTransferClient.GenericFileTransferService.GenericFileTransferService {
        
        public GenericFileTransferServiceClient() {
        }
        
        public GenericFileTransferServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GenericFileTransferServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenericFileTransferServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenericFileTransferServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GenericFileTransferClient.GenericFileTransferService.Report[] GetAllReports() {
            return base.Channel.GetAllReports();
        }
        
        public GenericFileTransferClient.GenericFileTransferService.Column[] GetColumnsByReport(System.Guid reportId) {
            return base.Channel.GetColumnsByReport(reportId);
        }
        
        public void UpsertReport(GenericFileTransferClient.GenericFileTransferService.Report report) {
            base.Channel.UpsertReport(report);
        }
        
        public void DeleteReport(GenericFileTransferClient.GenericFileTransferService.Report report) {
            base.Channel.DeleteReport(report);
        }
        
        public void UpsertColumn(GenericFileTransferClient.GenericFileTransferService.Column column) {
            base.Channel.UpsertColumn(column);
        }
        
        public void DeleteColumn(GenericFileTransferClient.GenericFileTransferService.Column column) {
            base.Channel.DeleteColumn(column);
        }
    }
}
