//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DbModel", "FK_Columns_Reporst", "Reports", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GenericFile.DataService.Report), "Columns", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GenericFile.DataService.Column), true)]
[assembly: EdmRelationshipAttribute("DbModel", "Fk_Transfer_Column", "Column", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GenericFile.DataService.Column), "Transfer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GenericFile.DataService.Transfer), true)]
[assembly: EdmRelationshipAttribute("DbModel", "FK_Transfer_Column2", "Column", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GenericFile.DataService.Column), "Transfer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GenericFile.DataService.Transfer), true)]
[assembly: EdmRelationshipAttribute("DbModel", "FK_Transfer_Report", "Report", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GenericFile.DataService.Report), "Transfer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GenericFile.DataService.Transfer), true)]
[assembly: EdmRelationshipAttribute("DbModel", "FK_Transfer_Report2", "Report", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(GenericFile.DataService.Report), "Transfer", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(GenericFile.DataService.Transfer), true)]

#endregion

namespace GenericFile.DataService
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DbEntities object using the connection string found in the 'DbEntities' section of the application configuration file.
        /// </summary>
        public DbEntities() : base("name=DbEntities", "DbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DbEntities object.
        /// </summary>
        public DbEntities(string connectionString) : base(connectionString, "DbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DbEntities object.
        /// </summary>
        public DbEntities(EntityConnection connection) : base(connection, "DbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Column> Columns
        {
            get
            {
                if ((_Columns == null))
                {
                    _Columns = base.CreateObjectSet<Column>("Columns");
                }
                return _Columns;
            }
        }
        private ObjectSet<Column> _Columns;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Report> Reports
        {
            get
            {
                if ((_Reports == null))
                {
                    _Reports = base.CreateObjectSet<Report>("Reports");
                }
                return _Reports;
            }
        }
        private ObjectSet<Report> _Reports;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Transfer> Transfers
        {
            get
            {
                if ((_Transfers == null))
                {
                    _Transfers = base.CreateObjectSet<Transfer>("Transfers");
                }
                return _Transfers;
            }
        }
        private ObjectSet<Transfer> _Transfers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TempTransfer> TempTransfers
        {
            get
            {
                if ((_TempTransfers == null))
                {
                    _TempTransfers = base.CreateObjectSet<TempTransfer>("TempTransfers");
                }
                return _TempTransfers;
            }
        }
        private ObjectSet<TempTransfer> _TempTransfers;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Columns EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToColumns(Column column)
        {
            base.AddObject("Columns", column);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Reports EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToReports(Report report)
        {
            base.AddObject("Reports", report);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Transfers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTransfers(Transfer transfer)
        {
            base.AddObject("Transfers", transfer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TempTransfers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTempTransfers(TempTransfer tempTransfer)
        {
            base.AddObject("TempTransfers", tempTransfer);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DbModel", Name="Column")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Column : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Column object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="reportId">Initial value of the ReportId property.</param>
        /// <param name="header">Initial value of the Header property.</param>
        /// <param name="position">Initial value of the Position property.</param>
        public static Column CreateColumn(global::System.Int32 id, global::System.Int32 reportId, global::System.String header, global::System.Int32 position)
        {
            Column column = new Column();
            column.Id = id;
            column.ReportId = reportId;
            column.Header = header;
            column.Position = position;
            return column;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ReportId
        {
            get
            {
                return _ReportId;
            }
            set
            {
                OnReportIdChanging(value);
                ReportPropertyChanging("ReportId");
                _ReportId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReportId");
                OnReportIdChanged();
            }
        }
        private global::System.Int32 _ReportId;
        partial void OnReportIdChanging(global::System.Int32 value);
        partial void OnReportIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Header
        {
            get
            {
                return _Header;
            }
            set
            {
                OnHeaderChanging(value);
                ReportPropertyChanging("Header");
                _Header = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Header");
                OnHeaderChanged();
            }
        }
        private global::System.String _Header;
        partial void OnHeaderChanging(global::System.String value);
        partial void OnHeaderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Position
        {
            get
            {
                return _Position;
            }
            set
            {
                OnPositionChanging(value);
                ReportPropertyChanging("Position");
                _Position = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Position");
                OnPositionChanged();
            }
        }
        private global::System.Int32 _Position;
        partial void OnPositionChanging(global::System.Int32 value);
        partial void OnPositionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbModel", "FK_Columns_Reporst", "Reports")]
        public Report Report
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Report>("DbModel.FK_Columns_Reporst", "Reports").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Report>("DbModel.FK_Columns_Reporst", "Reports").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Report> ReportReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Report>("DbModel.FK_Columns_Reporst", "Reports");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Report>("DbModel.FK_Columns_Reporst", "Reports", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbModel", "Fk_Transfer_Column", "Transfer")]
        public EntityCollection<Transfer> Transfers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Transfer>("DbModel.Fk_Transfer_Column", "Transfer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Transfer>("DbModel.Fk_Transfer_Column", "Transfer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbModel", "FK_Transfer_Column2", "Transfer")]
        public EntityCollection<Transfer> Transfers1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Transfer>("DbModel.FK_Transfer_Column2", "Transfer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Transfer>("DbModel.FK_Transfer_Column2", "Transfer", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DbModel", Name="Report")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Report : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Report object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="reportName">Initial value of the ReportName property.</param>
        /// <param name="header">Initial value of the Header property.</param>
        /// <param name="headerRow">Initial value of the HeaderRow property.</param>
        /// <param name="resultRow">Initial value of the ResultRow property.</param>
        public static Report CreateReport(global::System.Int32 id, global::System.String reportName, global::System.Boolean header, global::System.Int32 headerRow, global::System.Int32 resultRow)
        {
            Report report = new Report();
            report.Id = id;
            report.ReportName = reportName;
            report.Header = header;
            report.HeaderRow = headerRow;
            report.ResultRow = resultRow;
            return report;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ReportName
        {
            get
            {
                return _ReportName;
            }
            set
            {
                OnReportNameChanging(value);
                ReportPropertyChanging("ReportName");
                _ReportName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ReportName");
                OnReportNameChanged();
            }
        }
        private global::System.String _ReportName;
        partial void OnReportNameChanging(global::System.String value);
        partial void OnReportNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Header
        {
            get
            {
                return _Header;
            }
            set
            {
                OnHeaderChanging(value);
                ReportPropertyChanging("Header");
                _Header = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Header");
                OnHeaderChanged();
            }
        }
        private global::System.Boolean _Header;
        partial void OnHeaderChanging(global::System.Boolean value);
        partial void OnHeaderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HeaderRow
        {
            get
            {
                return _HeaderRow;
            }
            set
            {
                OnHeaderRowChanging(value);
                ReportPropertyChanging("HeaderRow");
                _HeaderRow = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HeaderRow");
                OnHeaderRowChanged();
            }
        }
        private global::System.Int32 _HeaderRow;
        partial void OnHeaderRowChanging(global::System.Int32 value);
        partial void OnHeaderRowChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ResultRow
        {
            get
            {
                return _ResultRow;
            }
            set
            {
                OnResultRowChanging(value);
                ReportPropertyChanging("ResultRow");
                _ResultRow = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ResultRow");
                OnResultRowChanged();
            }
        }
        private global::System.Int32 _ResultRow;
        partial void OnResultRowChanging(global::System.Int32 value);
        partial void OnResultRowChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Separator
        {
            get
            {
                return _Separator;
            }
            set
            {
                OnSeparatorChanging(value);
                ReportPropertyChanging("Separator");
                _Separator = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Separator");
                OnSeparatorChanged();
            }
        }
        private global::System.String _Separator;
        partial void OnSeparatorChanging(global::System.String value);
        partial void OnSeparatorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FileName
        {
            get
            {
                return _FileName;
            }
            set
            {
                OnFileNameChanging(value);
                ReportPropertyChanging("FileName");
                _FileName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FileName");
                OnFileNameChanged();
            }
        }
        private global::System.String _FileName;
        partial void OnFileNameChanging(global::System.String value);
        partial void OnFileNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SheetName
        {
            get
            {
                return _SheetName;
            }
            set
            {
                OnSheetNameChanging(value);
                ReportPropertyChanging("SheetName");
                _SheetName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SheetName");
                OnSheetNameChanged();
            }
        }
        private global::System.String _SheetName;
        partial void OnSheetNameChanging(global::System.String value);
        partial void OnSheetNameChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbModel", "FK_Columns_Reporst", "Columns")]
        public EntityCollection<Column> Columns
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Column>("DbModel.FK_Columns_Reporst", "Columns");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Column>("DbModel.FK_Columns_Reporst", "Columns", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbModel", "FK_Transfer_Report", "Transfer")]
        public EntityCollection<Transfer> Transfers
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Transfer>("DbModel.FK_Transfer_Report", "Transfer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Transfer>("DbModel.FK_Transfer_Report", "Transfer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbModel", "FK_Transfer_Report2", "Transfer")]
        public EntityCollection<Transfer> Transfers1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Transfer>("DbModel.FK_Transfer_Report2", "Transfer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Transfer>("DbModel.FK_Transfer_Report2", "Transfer", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DbModel", Name="TempTransfer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TempTransfer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TempTransfer object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="rowNumber">Initial value of the RowNumber property.</param>
        /// <param name="colIndex">Initial value of the ColIndex property.</param>
        /// <param name="value">Initial value of the Value property.</param>
        public static TempTransfer CreateTempTransfer(global::System.Int32 id, global::System.Int64 rowNumber, global::System.Int32 colIndex, global::System.String value)
        {
            TempTransfer tempTransfer = new TempTransfer();
            tempTransfer.Id = id;
            tempTransfer.RowNumber = rowNumber;
            tempTransfer.ColIndex = colIndex;
            tempTransfer.Value = value;
            return tempTransfer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 RowNumber
        {
            get
            {
                return _RowNumber;
            }
            set
            {
                OnRowNumberChanging(value);
                ReportPropertyChanging("RowNumber");
                _RowNumber = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RowNumber");
                OnRowNumberChanged();
            }
        }
        private global::System.Int64 _RowNumber;
        partial void OnRowNumberChanging(global::System.Int64 value);
        partial void OnRowNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ColIndex
        {
            get
            {
                return _ColIndex;
            }
            set
            {
                OnColIndexChanging(value);
                ReportPropertyChanging("ColIndex");
                _ColIndex = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ColIndex");
                OnColIndexChanged();
            }
        }
        private global::System.Int32 _ColIndex;
        partial void OnColIndexChanging(global::System.Int32 value);
        partial void OnColIndexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DbModel", Name="Transfer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Transfer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Transfer object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="columnFromId">Initial value of the ColumnFromId property.</param>
        /// <param name="columnToId">Initial value of the columnToId property.</param>
        /// <param name="reportFromId">Initial value of the ReportFromId property.</param>
        /// <param name="reportToId">Initial value of the ReportToId property.</param>
        /// <param name="colIndex">Initial value of the ColIndex property.</param>
        public static Transfer CreateTransfer(global::System.Int32 id, global::System.Int32 columnFromId, global::System.Int32 columnToId, global::System.Int32 reportFromId, global::System.Int32 reportToId, global::System.Int32 colIndex)
        {
            Transfer transfer = new Transfer();
            transfer.Id = id;
            transfer.ColumnFromId = columnFromId;
            transfer.columnToId = columnToId;
            transfer.ReportFromId = reportFromId;
            transfer.ReportToId = reportToId;
            transfer.ColIndex = colIndex;
            return transfer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ColumnFromId
        {
            get
            {
                return _ColumnFromId;
            }
            set
            {
                OnColumnFromIdChanging(value);
                ReportPropertyChanging("ColumnFromId");
                _ColumnFromId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ColumnFromId");
                OnColumnFromIdChanged();
            }
        }
        private global::System.Int32 _ColumnFromId;
        partial void OnColumnFromIdChanging(global::System.Int32 value);
        partial void OnColumnFromIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 columnToId
        {
            get
            {
                return _columnToId;
            }
            set
            {
                OncolumnToIdChanging(value);
                ReportPropertyChanging("columnToId");
                _columnToId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("columnToId");
                OncolumnToIdChanged();
            }
        }
        private global::System.Int32 _columnToId;
        partial void OncolumnToIdChanging(global::System.Int32 value);
        partial void OncolumnToIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ReportFromId
        {
            get
            {
                return _ReportFromId;
            }
            set
            {
                OnReportFromIdChanging(value);
                ReportPropertyChanging("ReportFromId");
                _ReportFromId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReportFromId");
                OnReportFromIdChanged();
            }
        }
        private global::System.Int32 _ReportFromId;
        partial void OnReportFromIdChanging(global::System.Int32 value);
        partial void OnReportFromIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ReportToId
        {
            get
            {
                return _ReportToId;
            }
            set
            {
                OnReportToIdChanging(value);
                ReportPropertyChanging("ReportToId");
                _ReportToId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ReportToId");
                OnReportToIdChanged();
            }
        }
        private global::System.Int32 _ReportToId;
        partial void OnReportToIdChanging(global::System.Int32 value);
        partial void OnReportToIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ColIndex
        {
            get
            {
                return _ColIndex;
            }
            set
            {
                OnColIndexChanging(value);
                ReportPropertyChanging("ColIndex");
                _ColIndex = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ColIndex");
                OnColIndexChanged();
            }
        }
        private global::System.Int32 _ColIndex;
        partial void OnColIndexChanging(global::System.Int32 value);
        partial void OnColIndexChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbModel", "Fk_Transfer_Column", "Column")]
        public Column Column
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Column>("DbModel.Fk_Transfer_Column", "Column").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Column>("DbModel.Fk_Transfer_Column", "Column").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Column> ColumnReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Column>("DbModel.Fk_Transfer_Column", "Column");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Column>("DbModel.Fk_Transfer_Column", "Column", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbModel", "FK_Transfer_Column2", "Column")]
        public Column Column1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Column>("DbModel.FK_Transfer_Column2", "Column").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Column>("DbModel.FK_Transfer_Column2", "Column").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Column> Column1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Column>("DbModel.FK_Transfer_Column2", "Column");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Column>("DbModel.FK_Transfer_Column2", "Column", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbModel", "FK_Transfer_Report", "Report")]
        public Report Report
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Report>("DbModel.FK_Transfer_Report", "Report").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Report>("DbModel.FK_Transfer_Report", "Report").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Report> ReportReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Report>("DbModel.FK_Transfer_Report", "Report");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Report>("DbModel.FK_Transfer_Report", "Report", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DbModel", "FK_Transfer_Report2", "Report")]
        public Report Report1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Report>("DbModel.FK_Transfer_Report2", "Report").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Report>("DbModel.FK_Transfer_Report2", "Report").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Report> Report1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Report>("DbModel.FK_Transfer_Report2", "Report");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Report>("DbModel.FK_Transfer_Report2", "Report", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
